### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by andfoy**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andfoy** [comment]
@conda-forge-admin, please re-render

**Comment by andfoy** [comment]
@conda-forge-admin, please re-render

**Comment by egpbos** [comment]
I haven't dealt with aarch64 before, so I find it hard to judge whether this is correct. Are you confident enough to say it works? I don't see a CI check for aarch64, for instance, shouldn't that be there?

Perhaps it would be helpful if you could join the maintenance crew for this feedstock. If you feel like this, please add your name to the list in recipe/meta.yaml (preferably in this PR) and I'll merge this. Then later, if something breaks, you can easily fix it yourself.

**Comment by andfoy** [comment]
Hi @egpbos, thanks for the reply, I reproduced the build on my local aarch64 machine and it works effectively,

**Pull request merged**
